version: '2'
services:
    web:
      container_name: sysm-web
      build: .
#      image: felixyin/sysm-web:latest
      volumes:
        - .:/code
      ports:
        - '8082:8080'
      links:
        - mysql
        - redis
    mysql:
      container_name: sysm-mysql
      build: ./docker/mysql/
#      image: felixyin/sysm-mysql
      ports:
        - '3307:3306'
      volumes:
        - ./docker/mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Ybkk1027
    redis:
      container_name: sysm-redis
      build: ./docker/redis/
#      image: felixyin/sysm-redis
      ports:
        - '6380:6379'
      volumes:
        - ./docker/redis/data:/data

